---
language: python
python: "2.7"
sudo: false

install:
  - pip install -r tests/requirements.yml
  - ansible-galaxy install git+file://$(pwd),$(git rev-parse --abbrev-ref HEAD) -p .molecule/roles
  - molecule dependency

script:
  - pre-commit run --all-files

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
