---
language: python
python: ["2.7", "3.5"]
dist: trusty
sudo: True
group: beta
env:
    global:
        - VBOX_MEMORY=2048
    matrix:
        - TOXENV=pre-commit
        - tox_switches="--platform openbsd60"
        - &openbsd59 tox_switches="--platform openbsd59"
        - tox_switches="--platform xenial"
        - tox_switches="--platform trusty"
        - tox_switches="--platform precise"
        - &stretch tox_switches="--platform stretch"
        - tox_switches="--platform jessie"
        - tox_switches="--platform wheezy"
matrix:
    fast_finish: True
    allow_failures:
        - python: "3.5"
        - env: *openbsd59
        - env: *stretch
cache:
  - pip
  - directories:
      - $HOME/.pre-commit

install:
  - sudo apt-get update
  - sudo apt-get install -y linux-headers-$(uname -r) virtualbox
  - wget https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
  - sudo dpkg -i vagrant_1.9.1_x86_64.deb
  - pip install tox-travis | cat

script:
  - travis_wait 45 tox -- $tox_switches

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
  on_failure: never
